### ISSUE TITLE
rst header incorrectly transformed - issues with Windows line endings

### ISSUE THREAD

**Issue by epogrebnyak** [telekom/style-doc#18]
```
Main
====
```

become

```
Main ====
```

after running style-doc and not longer recognised as header. I think this is not intended behaviour.

**Comment by PhilipMay** [comment]
Hey @epogrebnyak 
many thanks for reporting this. I will investigate it.

**Comment by epogrebnyak** [comment]
Maybe not tested on Windows and `\r\n` not appreciated?

**Comment by PhilipMay** [comment]
I can confirm it. It is a windows `\r\n` newline issue.
I added a test for linux encoding: 

https://github.com/telekom/style-doc/blob/34744cd145ac517a470ab978b7b390be6412ab63/tests/test_style_doc.py#L19

If you see a way how to fix it - feel free for a PR.

**Comment by PhilipMay** [comment]
It should be possible to read the file and convert all newlines to `\n` while reading it:
https://docs.python.org/3/library/functions.html#open

**Comment by PhilipMay** [comment]
@epogrebnyak this is fixed - see https://github.com/telekom/style-doc/commit/fbf9974f5357c4af45b8fb70a7d4f28d719d7dd4

**Comment by PhilipMay** [comment]
@epogrebnyak I made a new release on pypi. Can you please update the package and try it on your side?

**Comment by epogrebnyak** [comment]
Great, thanks, looks fixed. As a side comment the newlines after formatting the newlines are just `\n`, not `\r\n\` but I think one can live with that.
