### ISSUE TITLE
--max-len seems mandatory, not optional parameter

### ISSUE THREAD

**Issue by epogrebnyak** [telekom/style-doc#19]
I run ```style-doc . --check ``` and get an error while ```style-doc . --check `--max-len 80`` works. 

The error message is:

```
  File "c:\users\epogr\anaconda3\lib\site-packages\style_doc\style_doc.py", line 460, in style_docstring 
    if len(docstring) < max_len and "\n" not in docstring:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

**Comment by PhilipMay** [comment]
Yes. Thanks for reporting.
This is an error.
ArgumentParser should get an default value.

**Comment by PhilipMay** [comment]
@epogrebnyak this is fixed. A new release is on pypi:
https://pypi.org/project/style-doc/

Closing this. Feel free to reopen.
